export const EXAM_TYPES = ['JEE Main', 'JEE Advanced'];

export const CATEGORIES = [
  'EWS',
  'OPEN',
  'OPEN (PwD)',
  'EWS (PwD)',
  'OBC-NCL',
  'OBC-NCL (PwD)',
  'SC',
  'SC (PwD)',
  'ST',
  'ST (PwD)',
];

export const GENDERS = ['Gender-Neutral', 'Female-only'];

export const HOME_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];

export const BRANCH_OPTIONS = [
  'Aerospace Engineering',
  'Agricultural and Food Engineering',
  'Applied Geology',
  'Architecture',
  'Artificial Intelligence',
  'Artificial Intelligence and Data Science',
  'Artificial Intelligence and Machine Learning',
  'Bio Engineering',
  'Biotechnology',
  'Biomedical Engineering',
  'Ceramic Engineering',
  'Chemical Engineering',
  'Chemical Science and Technology',
  'Civil Engineering',
  'Computer Science and Engineering',
  'Computer Engineering',
  'Data Science and Artificial Intelligence',
  'Electrical Engineering',
  'Electrical and Electronics Engineering',
  'Electronics and Communication Engineering',
  'Electronics and Instrumentation Engineering',
  'Electronics Engineering',
  'Engineering Physics',
  'Environmental Engineering',
  'Food Engineering',
  'Industrial and Production Engineering',
  'Industrial Engineering',
  'Information Technology',
  'Instrumentation and Control Engineering',
  'Manufacturing Engineering',
  'Materials Engineering',
  'Mathematics and Computing',
  'Mechanical Engineering',
  'Metallurgical and Materials Engineering',
  'Metallurgical Engineering',
  'Mining Engineering',
  'Naval Architecture and Ocean Engineering',
  'Ocean Engineering',
  'Petroleum Engineering',
  'Pharmaceutical Engineering',
  'Physics',
  'Production Engineering',
  'Robotics and Artificial Intelligence',
  'Smart Manufacturing',
  'Textile Engineering',
  'Textile Technology',
];

export const COLLEGE_TYPES = ['IITs', 'NITs', 'IIITs', 'GFTIs'] as const;
export type CollegeType = typeof COLLEGE_TYPES[number];

export const COLLEGES_BY_TYPE: Record<CollegeType, string[]> = {
  IITs: [
    'Indian Institute of Technology Bombay',
    'Indian Institute of Technology Delhi',
    'Indian Institute of Technology Madras',
    'Indian Institute of Technology Kanpur',
    'Indian Institute of Technology Kharagpur',
    'Indian Institute of Technology Roorkee',
    'Indian Institute of Technology Guwahati',
    'Indian Institute of Technology Hyderabad',
    'Indian Institute of Technology Indore',
    'Indian Institute of Technology Bhubaneswar',
    'Indian Institute of Technology Jodhpur',
    'Indian Institute of Technology Patna',
    'Indian Institute of Technology Ropar',
    'Indian Institute of Technology Mandi',
    'Indian Institute of Technology Gandhinagar',
    'Indian Institute of Technology Tirupati',
    'Indian Institute of Technology Palakkad',
    'Indian Institute of Technology Dharwad',
    'Indian Institute of Technology Jammu',
    'Indian Institute of Technology Bhilai',
    'Indian Institute of Technology Goa',
    'Indian School of Mines Dhanbad',
  ],
  NITs: [
    'National Institute of Technology Tiruchirappalli',
    'National Institute of Technology Warangal',
    'National Institute of Technology Surathkal',
    'National Institute of Technology Calicut',
    'National Institute of Technology Rourkela',
    'National Institute of Technology Kurukshetra',
    'National Institute of Technology Durgapur',
    'National Institute of Technology Silchar',
    'National Institute of Technology Hamirpur',
    'National Institute of Technology Jamshedpur',
    'National Institute of Technology Patna',
    'National Institute of Technology Raipur',
    'National Institute of Technology Agartala',
    'National Institute of Technology Delhi',
    'National Institute of Technology Meghalaya',
    'National Institute of Technology Andhra Pradesh',
    'National Institute of Technology Arunachal Pradesh',
    'National Institute of Technology Goa',
    'National Institute of Technology Puducherry',
    'National Institute of Technology Sikkim',
    'National Institute of Technology Uttarakhand',
  ],
  IIITs: [
    'Indian Institute of Information Technology Allahabad',
    'Indian Institute of Information Technology Gwalior',
    'Indian Institute of Information Technology Jabalpur',
    'Indian Institute of Information Technology Kancheepuram',
    'Indian Institute of Information Technology Guwahati',
    'Indian Institute of Information Technology Kota',
    'Indian Institute of Information Technology Lucknow',
    'Indian Institute of Information Technology Pune',
    'Indian Institute of Information Technology Ranchi',
    'Indian Institute of Information Technology Sri City',
    'Indian Institute of Information Technology Vadodara',
    'Indian Institute of Information Technology Dharwad',
    'Indian Institute of Information Technology Nagpur',
    'Indian Institute of Information Technology Kalyani',
    'Indian Institute of Information Technology Una',
    'Indian Institute of Information Technology Bhagalpur',
    'Indian Institute of Information Technology Surat',
  ],
  GFTIs: [
    'Assam University, Silchar',
    'Birla Institute of Technology, Deoghar Off-Campus',
    'Birla Institute of Technology, Mesra, Ranchi',
    'Birla Institute of Technology, Patna Off-Campus',
    'CU Jharkhand',
    'Central University of Haryana',
    'Central University of Jammu',
    'Central University of Rajasthan, Rajasthan',
    'Central institute of Technology Kokrajar, Assam',
    'Chhattisgarh Swami Vivekanada Technical University, Bhilai (CSVTU Bhilai)',
    'Gati Shakti Vishwavidyalaya, Vadodara',
    'Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal',
    'Gurukula Kangri Vishwavidyalaya, Haridwar',
    'Indian Institute of Carpet Technology, Bhadohi',
    'Indian Institute of Handloom Technology(IIHT), Varanasi',
    'Indian Institute of Handloom Technology, Salem',
    'Institute of Chemical Technology, Mumbai: Indian Oil Odisha Campus, Bhubaneswar',
    'Institute of Engineering and Technology, Dr. H. S. Gour University. Sagar (A Central University)',
    'Institute of Infrastructure, Technology, Research and Management-Ahmedabad',
    'J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad',
    'Jawaharlal Nehru University, Delhi',
    'Mizoram University, Aizawl',
    'National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)',
    'National Institute of Food Technology Entrepreneurship and Management, Kundli',
    'Punjab Engineering College, Chandigarh',
    'School of Planning and Architecture, Bhopal',
    'School of Planning and Architecture, Delhi',
    'School of Planning and Architecture, Vijayawada',
    'Sant Longowal Institute of Engineering and Technology',
    'Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir',
    'Tezpur University, Napaam, Tezpur',
    'University of Hyderabad',
    'University of Jammu',
    'University of Rajasthan, Jaipur',
    'Vikram University, Ujjain',
  ],
};