export const EXAM_TYPES = ['JEE Main', 'JEE Advanced'];

export const CATEGORIES = [
  'EWS',
  'OPEN',
  'OPEN (PwD)',
  'EWS (PwD)',
  'OBC-NCL',
  'OBC-NCL (PwD)',
  'SC',
  'SC (PwD)',
  'ST',
  'ST (PwD)',
];

export const GENDERS = ['Gender-Neutral', 'Female-only'];

export const HOME_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];

// Full global branch list (used as fallback when no college is selected)
export const BRANCH_OPTIONS = [
  'Aeronautical Engineering',
  'Aerospace Engineering',
  'Agricultural And Food Engineering',
  'Agricultural Engineering',
  'Animation And VFX',
  'Applied Geology',
  'Applied Geophysics',
  'Artificial Intelligence',
  'Artificial Intelligence And Data Analytics',
  'Artificial Intelligence And Data Engineering',
  'Artificial Intelligence And Data Science',
  'Artificial Intelligence And Data Science Transportation And Logistics',
  'Artificial Intelligence And Machine Learning',
  'Aviation Engineering',
  'Bachelor Of Design',
  'Bio Engineering',
  'Bio Medical Engineering',
  'Bio Technology',
  'Biochemical Engineering',
  'Bioengineering',
  'Biological Engineering',
  'Biological Science',
  'Biological Sciences And Bioengineering',
  'Biomedical Engineering',
  'Biosciences And Bioengineering',
  'Biotechnology',
  'Biotechnology And Biochemical Engineering',
  'Biotechnology And Bioinformatics',
  'Carpet And Textile Technology',
  'Ceramic Engineering',
  'Chemical And Biochemical Engineering',
  'Chemical Engineering',
  'Chemical Science',
  'Chemical Science And Technology',
  'Chemical Sciences',
  'Chemical Technology',
  'Chemistry',
  'Chemistry With Specialization',
  'Civil And Environmental Engineering',
  'Civil And Infrastructure Engineering',
  'Civil Engineering',
  'Civil Engineering Rail Engineering',
  'Civil Engineering With Specialization In Construction Technology And Management',
  'Computational And Data Science',
  'Computational Engineering',
  'Computational Engineering And Mechanics',
  'Computational Mathematics',
  'Computer Engineering',
  'Computer Science',
  'Computer Science And Artificial Intelligence',
  'Computer Science And Business',
  'Computer Science And Engineering',
  'Computer Science And Engineering AI And ML',
  'Computer Science And Engineering Artificial Intelligence',
  'Computer Science And Engineering Artificial Intelligence And Data Science',
  'Computer Science And Engineering Artificial Intelligence And Machine Learning',
  'Computer Science And Engineering Artificial Intelligence And Machine Learning (Alternate)',
  'Computer Science And Engineering Cyber Physical System',
  'Computer Science And Engineering Cyber Security',
  'Computer Science And Engineering Data Science',
  'Computer Science And Engineering Data Science And Analytics',
  'Computer Science And Engineering Human Computer Interaction And Gaming Technology',
  'Computer Science And Engineering Internet Of Things, Cyber Security Including Block Chain Technology',
  'Computer Science And Engineering With Major In Artificial Intelligence',
  'Computer Science And Engineering With Minor In AI And ML',
  'Computer Science And Engineering With Specialization In Artificial Intelligence And Data Science',
  'Computer Science And Engineering With Specialization In Cyber Security',
  'Computer Science And Engineering With Specialization In Data Science',
  'Computer Science And Engineering With Specialization In Quantum Technologies',
  'Computer Science And Engineering With Specialization Of Data Science And Artificial Intelligence',
  'Dairy Engineering',
  'Data Science And Artificial Intelligence',
  'Data Science And Engineering',
  'Design',
  'Design Engineering',
  'Digital Agriculture',
  'Dual Degree',
  'Earth Sciences',
  'Economics',
  'Economics With MBA IIM Bodh Gaya',
  'Electrical And Electronics Engineering',
  'Electrical Engineering',
  'Electrical Engineering IC Design And Technology',
  'Electrical Engineering Integrated Circuit Design And Technology',
  'Electrical Engineering Power And Automation',
  'Electrical Engineering Rail Engineering',
  'Electrical Engineering With Specialization In Power System Engineering',
  'Electronic Engineering',
  'Electronics And Communication Engineering',
  'Electronics And Communication Engineering Avionics',
  'Electronics And Communication Engineering Internet Of Things',
  'Electronics And Communication Engineering Rail Engineering',
  'Electronics And Communication Engineering VLSI Design',
  'Electronics And Communication Engineering VLSI Design And Technology',
  'Electronics And Communication Engineering With Minor In Wearable Electronics',
  'Electronics And Communication Engineering With Specialization In Design And Manufacturing',
  'Electronics And Communication Engineering With Specialization In Microelectronics And VLSI System Design',
  'Electronics And Communication Engineering With Specialization In VLSI And Embedded Systems',
  'Electronics And Communication Engineering With Specialization Of Embedded Systems And Internet Of Things',
  'Electronics And Electrical Communication Engineering',
  'Electronics And Electrical Engineering',
  'Electronics And Instrumentation Engineering',
  'Electronics And Telecommunication Engineering',
  'Electronics And VLSI Engineering',
  'Electronics Engineering',
  'Electronics Engineering VLSI Design And Technology',
  'Energy And Electrical Vehicle Engineering',
  'Energy Engineering',
  'Engineering And Computational Mechanics',
  'Engineering Design',
  'Engineering Physics',
  'Engineering Science',
  'Environmental Engineering',
  'Environmental Science And Engineering',
  'Exploration Geophysics',
  'Fashion And Apparel Engineering',
  'Food Engineering And Technology',
  'Food Process Engineering',
  'Food Technology',
  'Food Technology And Management',
  'General Engineering',
  'Geological Technology',
  'Geophysical Technology',
  'Handloom And Textile Technology',
  'Industrial And Production Engineering',
  'Industrial And Systems Engineering',
  'Industrial Chemistry',
  'Industrial Design',
  'Industrial Engineering And Operations Research',
  'Industrial Internet Of Things',
  'Information Technology',
  'Information Technology-Business Informatics',
  'Instrumentation And Biomedical Engineering',
  'Instrumentation And Control Engineering',
  'Instrumentation Engineering',
  'Integrated B.Tech IT And M.Tech IT',
  'Integrated B.Tech IT And MBA',
  'Integrated Circuit Design And Technology',
  'Interdisciplinary Sciences',
  'Life Science',
  'Manufacturing Science And Engineering',
  'Material Science And Engineering',
  'Materials Engineering',
  'Materials Science And Engineering',
  'Materials Science And Metallurgical Engineering',
  'Materials Science And Technology',
  'Mathematics',
  'Mathematics And Computing',
  'Mathematics And Computing Technology',
  'Mathematics And Data Science',
  'Mathematics And Scientific Computing',
  'Mechanical Engineering',
  'Mechanical Engineering Rail Engineering',
  'Mechanical Engineering With Specialization In Design And Manufacturing',
  'Mechanical Engineering With Specialization In Manufacturing And Industrial Engineering',
  'Mechatronics And Automation Engineering',
  'Mechatronics Engineering',
  'Metallurgical And Materials Engineering',
  'Metallurgical Engineering',
  'Metallurgical Engineering And Materials Science',
  'Metallurgy And Materials Engineering',
  'Microelectronics And VLSI',
  'Microelectronics And VLSI Engineering',
  'Mineral And Metallurgical Engineering',
  'Mining Engineering',
  'Mining Machinery Engineering',
  'Petroleum Engineering',
  'Pharmaceutical Engineering And Technology',
  'Physical Science',
  'Physics',
  'Physics And Computational Engineering',
  'Physics With Specialization',
  'Printing And Packaging Technology',
  'Production And Industrial Engineering',
  'Production Engineering',
  'Quantitative Economics And Data Science',
  'Robotics And AI',
  'Robotics And Automation',
  'Smart Manufacturing',
  'Space Science And Engineering',
  'Statistics And Data Science',
  'Sustainable Energy Technologies',
  'Textile Technology',
  'VLSI Design And Technology',
];

export const COLLEGE_TYPES = ['IITs', 'NITs', 'IIITs', 'GFTIs'] as const;
export type CollegeType = typeof COLLEGE_TYPES[number];

export const COLLEGES_BY_TYPE: Record<CollegeType, string[]> = {
  IITs: [
    'Indian Institute of Technology (BHU) Varanasi',
    'Indian Institute of Technology (ISM) Dhanbad',
    'Indian Institute of Technology Bhilai',
    'Indian Institute of Technology Bhubaneswar',
    'Indian Institute of Technology Bombay',
    'Indian Institute of Technology Delhi',
    'Indian Institute of Technology Dharwad',
    'Indian Institute of Technology Gandhinagar',
    'Indian Institute of Technology Goa',
    'Indian Institute of Technology Guwahati',
    'Indian Institute of Technology Hyderabad',
    'Indian Institute of Technology Indore',
    'Indian Institute of Technology Jammu',
    'Indian Institute of Technology Jodhpur',
    'Indian Institute of Technology Kanpur',
    'Indian Institute of Technology Kharagpur',
    'Indian Institute of Technology Madras',
    'Indian Institute of Technology Mandi',
    'Indian Institute of Technology Palakkad',
    'Indian Institute of Technology Patna',
    'Indian Institute of Technology Roorkee',
    'Indian Institute of Technology Ropar',
    'Indian Institute of Technology Tirupati',
  ],
  NITs: [
    'Dr. B R Ambedkar National Institute of Technology, Jalandhar',
    'Indian Institute of Engineering Science and Technology, Shibpur',
    'Malaviya National Institute of Technology Jaipur',
    'Maulana Azad National Institute of Technology Bhopal',
    'Motilal Nehru National Institute of Technology Allahabad',
    'National Institute of Technology Agartala',
    'National Institute of Technology Arunachal Pradesh',
    'National Institute of Technology Calicut',
    'National Institute of Technology Delhi',
    'National Institute of Technology Durgapur',
    'National Institute of Technology Goa',
    'National Institute of Technology Hamirpur',
    'National Institute of Technology Karnataka, Surathkal',
    'National Institute of Technology Meghalaya',
    'National Institute of Technology Nagaland',
    'National Institute of Technology Patna',
    'National Institute of Technology Puducherry',
    'National Institute of Technology Raipur',
    'National Institute of Technology Sikkim',
    'National Institute of Technology, Andhra Pradesh',
    'National Institute of Technology, Jamshedpur',
    'National Institute of Technology, Kurukshetra',
    'National Institute of Technology, Manipur',
    'National Institute of Technology, Mizoram',
    'National Institute of Technology, Rourkela',
    'National Institute of Technology, Silchar',
    'National Institute of Technology, Srinagar',
    'National Institute of Technology, Tiruchirappalli',
    'National Institute of Technology, Uttarakhand',
    'National Institute of Technology, Warangal',
    'Sardar Vallabhbhai National Institute of Technology, Surat',
    'Visvesvaraya National Institute of Technology, Nagpur',
  ],
  IIITs: [
    'Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior',
    'INDIAN INSTITUTE OF INFORMATION TECHNOLOGY SENAPATI MANIPUR',
    'Indian Institute of Information Technology (IIIT) Nagpur',
    'Indian Institute of Information Technology (IIIT) Pune',
    'Indian Institute of Information Technology (IIIT) Ranchi',
    'Indian Institute of Information Technology (IIIT), Sri City, Chittoor',
    'Indian Institute of Information Technology (IIIT)Kota, Rajasthan',
    'Indian Institute of Information Technology Bhagalpur',
    'Indian Institute of Information Technology Bhopal',
    'Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh',
    'Indian Institute of Information Technology Guwahati',
    'Indian Institute of Information Technology Lucknow',
    'Indian Institute of Information Technology Surat',
    'Indian Institute of Information Technology Tiruchirappalli',
    'Indian Institute of Information Technology(IIIT) Dharwad',
    'Indian Institute of Information Technology(IIIT) Kalyani, West Bengal',
    'Indian Institute of Information Technology(IIIT) Kilohrad, Sonepat, Haryana',
    'Indian Institute of Information Technology(IIIT) Kottayam',
    'Indian Institute of Information Technology(IIIT) Una, Himachal Pradesh',
    'Indian Institute of Information Technology(IIIT), Vadodara, Gujrat',
    'Indian Institute of Information Technology, Agartala',
    'Indian Institute of Information Technology, Allahabad',
    'Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram',
    'Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD)',
    'Indian institute of information technology, Raichur, Karnataka',
    'International Institute of Information Technology, Bhubaneswar',
    'International Institute of Information Technology, Naya Raipur',
    'National Institute of Electronics and Information Technology, Ajmer (Rajasthan)',
    'National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)',
    'National Institute of Electronics and Information Technology, Gorakhpur (UP)',
    'National Institute of Electronics and Information Technology, Patna (Bihar)',
    'National Institute of Electronics and Information Technology, Ropar (Punjab)',
    'Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur',
  ],
  GFTIs: [
    'Assam University, Silchar',
    'Birla Institute of Technology, Deoghar Off-Campus',
    'Birla Institute of Technology, Mesra, Ranchi',
    'Birla Institute of Technology, Patna Off-Campus',
    'CU Jharkhand',
    'Central University of Haryana',
    'Central University of Jammu',
    'Central University of Rajasthan, Rajasthan',
    'Central institute of Technology Kokrajar, Assam',
    'Chhattisgarh Swami Vivekanada Technical University, Bhilai (CSVTU Bhilai)',
    'Gati Shakti Vishwavidyalaya, Vadodara',
    'Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal',
    'Gurukula Kangri Vishwavidyalaya, Haridwar',
    'Indian Institute of Carpet Technology, Bhadohi',
    'Indian Institute of Handloom Technology(IIHT), Varanasi',
    'Indian Institute of Handloom Technology, Salem',
    'Institute of Chemical Technology, Mumbai: Indian Oil Odisha Campus, Bhubaneswar',
    'Institute of Engineering and Technology, Dr. H. S. Gour University. Sagar (A Central University)',
    'Institute of Infrastructure, Technology, Research and Management-Ahmedabad',
    'J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad',
    'Jawaharlal Nehru University, Delhi',
    'Mizoram University, Aizawl',
    'National Institute of Advanced Manufacturing Technology, Ranchi',
    'National Institute of Food Technology Entrepreneurship and Management, Kundli',
    'National Institute of Food Technology Entrepreneurship and Management, Thanjavur',
    'North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar),Arunachal Pradesh',
    'North-Eastern Hill University, Shillong',
    'Puducherry Technological University, Puducherry',
    'Punjab Engineering College, Chandigarh',
    'Rajiv Gandhi National Aviation University, Fursatganj, Amethi (UP)',
    'Sant Longowal Institute of Engineering and Technology',
    'School of Engineering, Tezpur University, Napaam, Tezpur',
    'School of Studies of Engineering and Technology, Guru Ghasidas Vishwavidyalaya, Bilaspur',
    'Shri G. S. Institute of Technology and Science Indore',
    'Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir',
    'University of Hyderabad',
  ],
};

// ─── College → Branch mapping (derived from the JoSAA 2026 dataset) ─────────
// Every entry here corresponds exactly to the branches present in the cutoff
// data for that college. The branch dropdown in PredictorForm filters this
// record by the currently-selected college name.
export const BRANCHES_BY_COLLEGE: Record<string, string[]> = {
  'Assam University, Silchar': [
    'Agricultural Engineering',
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
  ],
  'Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior': [
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Integrated B. Tech.It And M. Tech It',
    'Integrated B. Tech.It And Mba',
    'Mathematics And Scientific Computing',
  ],
  'Birla Institute of Technology, Deoghar Off-Campus': [
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
  ],
  'Birla Institute of Technology, Mesra, Ranchi': [
    'Artificial Intelligence And Machine Learning',
    'Bio Technology',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Food Engineering And Technology',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Physics',
    'Production And Industrial Engineering',
    'Quantitative Economics And Data Science',
  ],
  'Birla Institute of Technology, Patna Off-Campus': [
    'Artificial Intelligence And Machine Learning',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
  ],
  'CU Jharkhand': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Metallurgical And Materials Engineering',
  ],
  'Central University of Haryana': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Printing And Packaging Technology',
  ],
  'Central University of Jammu': [
    'Computer Science And Engineering',
    'Computer Science And Engineering With Specialization In Cyber Security',
    'Electronics And Communication Engineering',
    'Electronics And Communication Engineering Avionics',
    'Mathematics And Computing',
  ],
  'Central University of Rajasthan, Rajasthan': [
    'Bio Medical Engineering',
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
  ],
  'Central institute of Technology Kokrajar, Assam': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
    'Food Engineering And Technology',
    'Instrumentation Engineering',
  ],
  'Chhattisgarh Swami Vivekanada Technical University, Bhilai (CSVTU Bhilai)': [
    'Civil Engineering',
    'Computer Science And Engineering Artificial Intelligence',
    'Computer Science And Engineering Data Science',
  ],
  'Dr. B R Ambedkar National Institute of Technology, Jalandhar': [
    'Bio Technology',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Data Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Electronics And Vlsi Engineering',
    'Industrial And Production Engineering',
    'Information Technology',
    'Instrumentation And Control Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Textile Technology',
  ],
  'Gati Shakti Vishwavidyalaya, Vadodara': [
    'Artificial Intelligence And Data Science Transportation And Logistics',
    'Aviation Engineering',
    'Civil Engineering Rail Engineering',
    'Electrical Engineering Rail Engineering',
    'Electronics And Communication Engineering Rail Engineering',
    'Mechanical Engineering Rail Engineering',
  ],
  'Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal': [
    'Civil And Environmental Engineering',
    'Computer Science And Engineering Artificial Intelligence And Machine Learning',
    'Electrical Engineering',
    'Food Technology',
    'Mechanical Engineering',
  ],
  'Gurukula Kangri Vishwavidyalaya, Haridwar': [
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
  ],
  'INDIAN INSTITUTE OF INFORMATION TECHNOLOGY SENAPATI MANIPUR': [
    'Computer Science And Engineering',
    'Computer Science And Engineering With Specialization In Artificial Intelligence And Data Science',
    'Computer Science And Engineering With Specialization In Cyber Security',
    'Computer Science And Engineering With Specialization In Quantum Technologies',
    'Electronics And Communication Engineering',
    'Electronics And Communication Engineering With Specialization In VLSI And Embedded Systems',
  ],
  'Indian Institute of Carpet Technology, Bhadohi': [
    'Carpet And Textile Technology',
  ],
  'Indian Institute of Engineering Science and Technology, Shibpur': [
    'Aerospace Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Telecommunication Engineering',
    'Information Technology',
    'Mechanical Engineering',
    'Metallurgy And Materials Engineering',
    'Mining Engineering',
  ],
  'Indian Institute of Handloom Technology(IIHT), Varanasi': [
    'Handloom And Textile Technology',
  ],
  'Indian Institute of Handloom Technology, Salem': [
    'Handloom And Textile Technology',
  ],
  'Indian Institute of Information Technology (IIIT) Nagpur': [
    'Computer Science And Engineering',
    'Computer Science And Engineering Artificial Intelligence And Machine Learning',
    'Computer Science And Engineering Data Science And Analytics',
    'Computer Science And Engineering Human Computer Interaction And Gaming Technology',
    'Electronics And Communication Engineering',
    'Electronics And Communication Engineering Internet Of Things',
  ],
  'Indian Institute of Information Technology (IIIT) Pune': [
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
  ],
  'Indian Institute of Information Technology (IIIT) Ranchi': [
    'Computer Science And Engineering',
    'Computer Science And Engineering With Specialization Of Data Science And Artificial Intelligence',
    'Electronics And Communication Engineering',
    'Electronics And Communication Engineering With Specialization Of Embedded Systems And Internet Of Things',
    'Mathematics And Computing',
  ],
  'Indian Institute of Information Technology (IIIT), Sri City, Chittoor': [
    'Artificial Intelligence And Data Science',
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
  ],
  'Indian Institute of Information Technology (IIIT)Kota, Rajasthan': [
    'Artificial Intelligence And Data Engineering',
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
  ],
  'Indian Institute of Information Technology Bhagalpur': [
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
    'Mathematics And Computing',
    'Mechatronics And Automation Engineering',
  ],
  'Indian Institute of Information Technology Bhopal': [
    'Computer Science And Engineering',
    'Computer Science And Engineering Artificial Intelligence',
    'Computer Science And Engineering Cyber Physical System',
    'Computer Science And Engineering Cyber Security',
    'Computer Science And Engineering Data Science',
    'Electronics And Communication Engineering',
    'Information Technology',
    'Mathematics And Computing',
    'Physics And Computational Engineering',
  ],
  'Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh': [
    'Artificial Intelligence And Data Science',
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
    'Electronics And Communication Engineering With Specialization In Design And Manufacturing',
    'Mechanical Engineering',
    'Mechanical Engineering With Specialization In Design And Manufacturing',
  ],
  'Indian Institute of Information Technology Guwahati': [
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
  ],
  'Indian Institute of Information Technology Lucknow': [
    'Computer Science',
    'Computer Science And Artificial Intelligence',
    'Computer Science And Business',
    'Information Technology',
  ],
  'Indian Institute of Information Technology Surat': [
    'Computer Science And Engineering',
    'Computer Science And Engineering Artificial Intelligence And Machine Learning',
    'Computer Science And Engineering Cyber Security',
    'Electronics And Communication Engineering',
  ],
  'Indian Institute of Information Technology Tiruchirappalli': [
    'Computer Science And Engineering',
    'Computer Science And Engineering Artificial Intelligence And Data Science',
    'Electronics And Communication Engineering',
    'Electronics And Communication Engineering VLSI Design',
  ],
  'Indian Institute of Information Technology(IIIT) Dharwad': [
    'Computer Science And Engineering',
    'Data Science And Artificial Intelligence',
    'Electronics And Communication Engineering',
  ],
  'Indian Institute of Information Technology(IIIT) Kalyani, West Bengal': [
    'Computer Science And Engineering',
    'Computer Science And Engineering Artificial Intelligence And Data Science',
    'Computer Science And Engineering Cyber Security',
    'Electronics And Communication Engineering',
  ],
  'Indian Institute of Information Technology(IIIT) Kilohrad, Sonepat, Haryana': [
    'Computer Science And Engineering',
    'Computer Science And Engineering Data Science And Analytics',
    'Information Technology',
  ],
  'Indian Institute of Information Technology(IIIT) Kottayam': [
    'Computer Science And Engineering',
    'Computer Science And Engineering With Specialization In Artificial Intelligence And Data Science',
    'Computer Science And Engineering With Specialization In Cyber Security',
    'Electronics And Communication Engineering',
  ],
  'Indian Institute of Information Technology(IIIT) Una, Himachal Pradesh': [
    'Computer Science And Engineering',
    'Computer Science And Engineering Cyber Security',
    'Computer Science And Engineering Data Science',
    'Electronics And Communication Engineering',
  ],
  'Indian Institute of Information Technology(IIIT), Vadodara, Gujrat': [
    'Artificial Intelligence',
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
    'Information Technology',
  ],
  'Indian Institute of Information Technology, Agartala': [
    'Computer Science And Engineering',
  ],
  'Indian Institute of Information Technology, Allahabad': [
    'Electronics And Communication Engineering',
    'Information Technology',
    'Information Technology-Business Informatics',
  ],
  'Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram': [
    'Computer Science And Engineering',
    'Computer Science And Engineering With Major In Artificial Intelligence',
    'Design Engineering',
    'Electronics And Communication Engineering',
    'Engineering Physics',
    'Mechanical Engineering',
    'Smart Manufacturing',
  ],
  'Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD)': [
    'Artificial Intelligence',
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
  ],
  'Indian Institute of Technology (BHU) Varanasi': [
    'Biochemical Engineering',
    'Bioengineering',
    'Ceramic Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics Engineering',
    'Engineering Physics',
    'Industrial Chemistry',
    'Materials Science And Technology',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Metallurgical Engineering',
    'Mining Engineering',
    'Pharmaceutical Engineering And Technology',
  ],
  'Indian Institute of Technology (ISM) Dhanbad': [
    'Applied Geology',
    'Applied Geophysics',
    'Chemical Engineering',
    'Chemical Science',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Engineering Physics',
    'Environmental Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Mineral And Metallurgical Engineering',
    'Mining Engineering',
    'Mining Machinery Engineering',
    'Petroleum Engineering',
    'Physical Science',
  ],
  'Indian Institute of Technology Bhilai': [
    'Computer Science And Engineering',
    'Data Science And Artificial Intelligence',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Materials Science And Metallurgical Engineering',
    'Mechanical Engineering',
    'Mechatronics Engineering',
  ],
  'Indian Institute of Technology Bhubaneswar': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Engineering Physics',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
  ],
  'Indian Institute of Technology Bombay': [
    'Aerospace Engineering',
    'Applied Geophysics',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Economics',
    'Electrical Engineering',
    'Energy Engineering',
    'Engineering Physics',
    'Environmental Science And Engineering',
    'Industrial Engineering And Operations Research',
    'Mathematics',
    'Mechanical Engineering',
    'Metallurgical Engineering And Materials Science',
  ],
  'Indian Institute of Technology Delhi': [
    'Biotechnology And Biochemical Engineering',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Design',
    'Electrical Engineering',
    'Electrical Engineering Power And Automation',
    'Energy Engineering',
    'Engineering And Computational Mechanics',
    'Engineering Physics',
    'Materials Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Production And Industrial Engineering',
    'Textile Technology',
  ],
  'Indian Institute of Technology Dharwad': [
    'Chemical And Biochemical Engineering',
    'Civil And Infrastructure Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Engineering Physics',
    'Interdisciplinary Sciences',
    'Mathematics And Computing',
    'Mechanical Engineering',
  ],
  'Indian Institute of Technology Gandhinagar': [
    'Artificial Intelligence',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Integrated Circuit Design And Technology',
    'Materials Engineering',
    'Mechanical Engineering',
  ],
  'Indian Institute of Technology Goa': [
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
  ],
  'Indian Institute of Technology Guwahati': [
    'Biosciences And Bioengineering',
    'Chemical Engineering',
    'Chemical Science And Technology',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Data Science And Artificial Intelligence',
    'Electronics And Communication Engineering',
    'Electronics And Electrical Engineering',
    'Energy Engineering',
    'Engineering Physics',
    'Mathematics And Computing',
    'Mechanical Engineering',
  ],
  'Indian Institute of Technology Hyderabad': [
    'Artificial Intelligence',
    'Biomedical Engineering',
    'Biotechnology And Bioinformatics',
    'Chemical Engineering',
    'Civil Engineering',
    'Computational Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electrical Engineering IC Design And Technology',
    'Engineering Physics',
    'Engineering Science',
    'Industrial Chemistry',
    'Materials Science And Metallurgical Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
  ],
  'Indian Institute of Technology Indore': [
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Engineering Physics',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Metallurgical Engineering And Materials Science',
    'Space Science And Engineering',
  ],
  'Indian Institute of Technology Jammu': [
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Engineering Physics',
    'Materials Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
  ],
  'Indian Institute of Technology Jodhpur': [
    'Artificial Intelligence And Data Science',
    'Bio Engineering',
    'Chemical Engineering',
    'Chemistry With Specialization',
    'Civil And Infrastructure Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics Engineering',
    'Materials Engineering',
    'Mechanical Engineering',
    'Physics With Specialization',
  ],
  'Indian Institute of Technology Kanpur': [
    'Aerospace Engineering',
    'Biological Sciences And Bioengineering',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Earth Sciences',
    'Economics',
    'Electrical Engineering',
    'Materials Science And Engineering',
    'Mathematics And Scientific Computing',
    'Mechanical Engineering',
    'Physics',
    'Statistics And Data Science',
  ],
  'Indian Institute of Technology Kharagpur': [
    'Aerospace Engineering',
    'Agricultural And Food Engineering',
    'Applied Geology',
    'Artificial Intelligence',
    'Biotechnology And Biochemical Engineering',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Economics',
    'Electrical Engineering',
    'Electronics And Electrical Communication Engineering',
    'Exploration Geophysics',
    'Industrial And Systems Engineering',
    'Instrumentation Engineering',
    'Manufacturing Science And Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
    'Mining Engineering',
    'Physics',
  ],
  'Indian Institute of Technology Madras': [
    'Aerospace Engineering',
    'Artificial Intelligence And Data Analytics',
    'Biological Engineering',
    'Biological Science',
    'Chemical Engineering',
    'Civil Engineering',
    'Computational Engineering And Mechanics',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Engineering Design',
    'Engineering Physics',
    'Instrumentation And Biomedical Engineering',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
    'Physics',
  ],
  'Indian Institute of Technology Mandi': [
    'Bio Engineering',
    'Chemical Sciences',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Data Science And Artificial Intelligence',
    'Electrical Engineering',
    'Engineering Physics',
    'General Engineering',
    'Materials Science And Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Microelectronics And VLSI',
  ],
  'Indian Institute of Technology Palakkad': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Data Science And Engineering',
    'Electrical Engineering',
    'Mechanical Engineering',
  ],
  'Indian Institute of Technology Patna': [
    'Artificial Intelligence And Data Science',
    'Chemical Engineering',
    'Chemical Science And Technology',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Economics',
    'Economics With MBA IIM Bodh Gaya',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Engineering Physics',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
  ],
  'Indian Institute of Technology Roorkee': [
    'Biosciences And Bioengineering',
    'Chemical Engineering',
    'Chemical Sciences',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Data Science And Artificial Intelligence',
    'Economics',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Energy Engineering',
    'Engineering Physics',
    'Geological Technology',
    'Geophysical Technology',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
    'Physics',
    'Production And Industrial Engineering',
  ],
  'Indian Institute of Technology Ropar': [
    'Artificial Intelligence And Data Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Digital Agriculture',
    'Electrical Engineering',
    'Electrical Engineering Integrated Circuit Design And Technology',
    'Engineering Physics',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
  ],
  'Indian Institute of Technology Tirupati': [
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Engineering Physics',
    'Mechanical Engineering',
  ],
  'Indian institute of information technology, Raichur, Karnataka': [
    'Artificial Intelligence And Data Science',
    'Computer Science And Engineering',
    'Mathematics And Computing',
  ],
  'Institute of Chemical Technology, Mumbai: Indian Oil Odisha Campus, Bhubaneswar': [
    'Chemical Engineering',
  ],
  'Institute of Engineering and Technology, Dr. H. S. Gour University. Sagar (A Central University)': [
    'Aeronautical Engineering',
    'Computer Science And Engineering',
    'Dairy Engineering',
    'Electronics And Communication Engineering',
    'Fashion And Apparel Engineering',
    'Food Engineering And Technology',
  ],
  'Institute of Infrastructure, Technology, Research and Management-Ahmedabad': [
    'Civil Engineering',
    'Computer Engineering',
    'Electrical Engineering',
    'Mechanical Engineering',
  ],
  'International Institute of Information Technology, Bhubaneswar': [
    'Computer Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Telecommunication Engineering',
    'Information Technology',
  ],
  'International Institute of Information Technology, Naya Raipur': [
    'Computer Science And Engineering',
    'Data Science And Artificial Intelligence',
    'Electronics And Communication Engineering',
  ],
  'J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad': [
    'Computer Science And Engineering With Major In Artificial Intelligence',
    'Electronics And Communication Engineering',
  ],
  'Jawaharlal Nehru University, Delhi': [
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
  ],
  'Malaviya National Institute of Technology Jaipur': [
    'Artificial Intelligence And Data Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
  ],
  'Maulana Azad National Institute of Technology Bhopal': [
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Dual Degree',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Energy And Electrical Vehicle Engineering',
    'Materials Science And Metallurgical Engineering',
    'Mathematics And Data Science',
    'Mechanical Engineering',
  ],
  'Mizoram University, Aizawl': [
    'Civil Engineering',
    'Computer Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Information Technology',
  ],
  'Motilal Nehru National Institute of Technology Allahabad': [
    'Bio Technology',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Engineering And Computational Mechanics',
    'Materials Engineering',
    'Mechanical Engineering',
    'Production And Industrial Engineering',
  ],
  'National Institute of Advanced Manufacturing Technology, Ranchi': [
    'Computer Engineering',
    'Mechanical Engineering',
    'Metallurgy And Materials Engineering',
    'Production And Industrial Engineering',
  ],
  'National Institute of Electronics and Information Technology, Ajmer (Rajasthan)': [
    'Computer Science And Engineering Internet Of Things, Cyber Security Including Block Chain Technology',
  ],
  'National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)': [
    'Computer Science And Engineering',
    'Electronic Engineering',
  ],
  'National Institute of Electronics and Information Technology, Gorakhpur (UP)': [
    'Computer Science And Engineering With Minor In AI And ML',
    'Electronics And Communication Engineering With Minor In Wearable Electronics',
  ],
  'National Institute of Electronics and Information Technology, Patna (Bihar)': [
    'Computer Science And Engineering',
  ],
  'National Institute of Electronics and Information Technology, Ropar (Punjab)': [
    'Computer Science And Engineering AI And ML',
  ],
  'National Institute of Food Technology Entrepreneurship and Management, Kundli': [
    'Food Technology And Management',
  ],
  'National Institute of Food Technology Entrepreneurship and Management, Thanjavur': [
    'Food Technology',
  ],
  'National Institute of Technology Agartala': [
    'Biotechnology And Biochemical Engineering',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Computational Mathematics',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Electronics And Instrumentation Engineering',
    'Engineering Physics',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Physics',
    'Production Engineering',
  ],
  'National Institute of Technology Arunachal Pradesh': [
    'Biosciences And Bioengineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
  ],
  'National Institute of Technology Calicut': [
    'Bio Technology',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Energy Engineering',
    'Engineering Physics',
    'Materials Science And Engineering',
    'Mechanical Engineering',
    'Production Engineering',
  ],
  'National Institute of Technology Delhi': [
    'Aerospace Engineering',
    'Artificial Intelligence And Data Science',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
    'VLSI Design And Technology',
  ],
  'National Institute of Technology Durgapur': [
    'Bio Technology',
    'Biotechnology',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
  ],
  'National Institute of Technology Goa': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
  ],
  'National Institute of Technology Hamirpur': [
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Engineering Physics',
    'Materials Science And Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
  ],
  'National Institute of Technology Karnataka, Surathkal': [
    'Artificial Intelligence',
    'Chemical Engineering',
    'Civil Engineering',
    'Computational And Data Science',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Information Technology',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
    'Mining Engineering',
  ],
  'National Institute of Technology Meghalaya': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
  ],
  'National Institute of Technology Nagaland': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Electronics And Instrumentation Engineering',
    'Mechanical Engineering',
  ],
  'National Institute of Technology Patna': [
    'Artificial Intelligence And Data Science',
    'Chemical Technology',
    'Civil Engineering',
    'Civil Engineering With Specialization In Construction Technology And Management',
    'Computer Science And Engineering',
    'Computer Science And Engineering With Specialization In Cyber Security',
    'Computer Science And Engineering With Specialization In Data Science',
    'Electrical Engineering',
    'Electrical Engineering With Specialization In Power System Engineering',
    'Electronics And Communication Engineering',
    'Electronics And Communication Engineering With Specialization In Microelectronics And VLSI System Design',
    'Electronics Engineering VLSI Design And Technology',
    'Material Science And Engineering',
    'Mathematics And Computing Technology',
    'Mechanical Engineering',
    'Mechanical Engineering With Specialization In Manufacturing And Industrial Engineering',
    'Mechatronics And Automation Engineering',
  ],
  'National Institute of Technology Puducherry': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
  ],
  'National Institute of Technology Raipur': [
    'Bio Medical Engineering',
    'Bio Technology',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Information Technology',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
    'Mining Engineering',
  ],
  'National Institute of Technology Sikkim': [
    'Artificial Intelligence And Machine Learning',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
  ],
  'National Institute of Technology, Andhra Pradesh': [
    'Bio Technology',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
  ],
  'National Institute of Technology, Jamshedpur': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Engineering And Computational Mechanics',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
    'Production And Industrial Engineering',
  ],
  'National Institute of Technology, Kurukshetra': [
    'Artificial Intelligence And Data Science',
    'Artificial Intelligence And Machine Learning',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Industrial Internet Of Things',
    'Information Technology',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Microelectronics And VLSI Engineering',
    'Production And Industrial Engineering',
    'Robotics And Automation',
    'Sustainable Energy Technologies',
  ],
  'National Institute of Technology, Manipur': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
  ],
  'National Institute of Technology, Mizoram': [
    'Chemical Science And Technology',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
  ],
  'National Institute of Technology, Rourkela': [
    'Artificial Intelligence',
    'Bio Medical Engineering',
    'Bio Technology',
    'Ceramic Engineering',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Electronics And Instrumentation Engineering',
    'Food Process Engineering',
    'Industrial Design',
    'Life Science',
    'Mathematics',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
    'Mining Engineering',
    'Physics',
  ],
  'National Institute of Technology, Silchar': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Electronics And Instrumentation Engineering',
    'Mechanical Engineering',
  ],
  'National Institute of Technology, Srinagar': [
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Information Technology',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
  ],
  'National Institute of Technology, Tiruchirappalli': [
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Instrumentation And Control Engineering',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
    'Production Engineering',
  ],
  'National Institute of Technology, Uttarakhand': [
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
  ],
  'National Institute of Technology, Warangal': [
    'Bio Technology',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Computer Science And Engineering Artificial Intelligence And Data Science',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Electronics And Communication Engineering VLSI Design And Technology',
    'Mathematics',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
    'Physics',
  ],
  'North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar),Arunachal Pradesh': [
    'Agricultural Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
  ],
  'North-Eastern Hill University, Shillong': [
    'Biomedical Engineering',
    'Electronics And Communication Engineering',
    'Energy Engineering',
    'Information Technology',
  ],
  'Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur': [
    'Computer Science And Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
    'Smart Manufacturing',
  ],
  'Puducherry Technological University, Puducherry': [
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Electronics And Instrumentation Engineering',
    'Information Technology',
    'Mechanical Engineering',
    'Mechatronics Engineering',
  ],
  'Punjab Engineering College, Chandigarh': [
    'Aerospace Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Computer Science And Engineering Artificial Intelligence',
    'Computer Science And Engineering Data Science',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Electronics Engineering VLSI Design And Technology',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
    'Production And Industrial Engineering',
  ],
  'Rajiv Gandhi National Aviation University, Fursatganj, Amethi (UP)': [
    'Aerospace Engineering',
    'Electronics And Communication Engineering Avionics',
  ],
  'Sant Longowal Institute of Engineering and Technology': [
    'Artificial Intelligence And Data Science',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Food Technology',
    'Instrumentation And Control Engineering',
    'Mathematics',
    'Mechanical Engineering',
    'Physics',
  ],
  'Sardar Vallabhbhai National Institute of Technology, Surat': [
    'Artificial Intelligence',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Electronics And VLSI Engineering',
    'Engineering Physics',
    'Industrial Chemistry',
    'Mathematics',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Physics',
  ],
  'School of Engineering, Tezpur University, Napaam, Tezpur': [
    'Bachelor Of Design',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Food Engineering And Technology',
    'Mechanical Engineering',
  ],
  'School of Studies of Engineering and Technology, Guru Ghasidas Vishwavidyalaya, Bilaspur': [
    'Animation And VFX',
    'Artificial Intelligence And Data Science',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Industrial And Production Engineering',
    'Information Technology',
    'Mechanical Engineering',
  ],
  'Shri G. S. Institute of Technology and Science Indore': [
    'Biomedical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Instrumentation Engineering',
    'Electronics And Telecommunication Engineering',
    'Industrial And Production Engineering',
    'Information Technology',
    'Mechanical Engineering',
  ],
  'Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir': [
    'Bio Technology',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical Engineering',
    'Electronics And Communication Engineering',
    'Mathematics And Computing',
    'Mechanical Engineering',
    'Robotics And AI',
  ],
  'University of Hyderabad': [
    'Computer Science And Engineering',
    'Materials Engineering',
  ],
  'Visvesvaraya National Institute of Technology, Nagpur': [
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Science And Engineering',
    'Electrical And Electronics Engineering',
    'Electronics And Communication Engineering',
    'Mechanical Engineering',
    'Metallurgical And Materials Engineering',
    'Mining Engineering',
  ],
};