'use client';

import SliderRow from './SliderRow';

interface Weights {
  hometown: number;
  college: number;
  branch: number;
}

export default function PrioritySliders({
  weights,
  onChange,
  onGenerate,
  generated,
  loading,
}: {
  weights: Weights;
  onChange: (key: keyof Weights, value: number) => void;
  onGenerate: () => void;
  generated: boolean;
  loading: boolean;
}) {
  const total = weights.hometown + weights.college + weights.branch;

  return (
    <div className="flex flex-col gap-6">
      <div className="space-y-4">
        <h3 className="font-bold text-xs uppercase tracking-widest text-gray-500 px-1">Set Your Priorities</h3>
        <div className="brutal-border p-8 rounded-xl bg-white space-y-8 shadow-[4px_4px_0px_#0A0A0A]">
          <SliderRow
            label="Hometown Locality"
            value={weights.hometown}
            onChange={(v) => onChange('hometown', v)}
          />
          <SliderRow
            label="College Priority"
            value={weights.college}
            onChange={(v) => onChange('college', v)}
          />
          <SliderRow
            label="Branch Priority"
            value={weights.branch}
            onChange={(v) => onChange('branch', v)}
          />

          <div className="pt-6 border-t-2 border-dashed border-gray-200 flex justify-between items-center">
            <span className="text-xs font-bold uppercase text-gray-500">
              {total === 100 ? 'Balanced Weightage' : 'Total (should be 100%)'}
            </span>
            <span className={`text-xl font-bold ${total === 100 ? 'text-[#059669]' : 'text-red-500'}`}>
              {total}%
            </span>
          </div>
        </div>
      </div>

      <button
        onClick={onGenerate}
        disabled={loading}
        className="w-full bg-[#059669] text-white font-bold py-4 brutal-border rounded-xl shadow-[4px_4px_0px_#0A0A0A] hover:shadow-none hover:translate-x-[1px] hover:translate-y-[1px] transition-all flex items-center justify-center gap-2 group disabled:opacity-70"
      >
        <span className="material-symbols-outlined group-hover:rotate-12 transition-transform">
          {generated ? 'check_circle' : 'auto_fix_high'}
        </span>

        {
          loading
            ? 'Generating...'
            : generated
              ? 'Generate The List'
              : 'Generate Recommended List'
        }
      </button>

      <div className="mt-4 flex items-start gap-3 p-4 bg-emerald-50/50 brutal-border rounded-xl border-[#059669]/20">
        <span className="material-symbols-outlined text-[#059669] text-xl">info</span>
        <p className="text-xs text-gray-600 leading-relaxed font-medium">
          <span className="font-bold text-[#059669]">Note:</span> These rankings are generated by AI models based on historical trends and may not be 100% accurate. Please use them as a guide.
        </p>
      </div>
    </div>
  );
}